### ISSUE TITLE
Normalization of model distributions

### ISSUE THREAD

**Issue by stestoll** [luisfabib/DeerAnalysis2#41] opened 2020-03-18 20:44 UTC
Currently, distributions models are manually re-normalized over the distance range provided in the input vector `r`.

This is identical to normalization over r=(0,inf) as long as the entire mass of the distribution is contained within `r`. If not, then the normalization will differ. Here is an example:
```matlab
param = [3 2];
r1 = linspace(2,6);
r2 = linspace(0,6);
P1 = rd_onegaussian(r1,param);
P2 = rd_onegaussian(r2,param);
plot(r1,P1,r2,P2);
grid on
```
`P1` and `P2` have different normalization, even though they are the same model.

This means that a P evaluated over a r range is implicitly treated as a truncated P with P=0 outside the provided r range, instead of the P defined according to the analytical expression of the model, just evaluated over a limited r range.

There are two situations where the model functions are used:
* The user wants to a look at a distribution.
* The distribution model function is called by a fit function. In this case, the distance range should always be chosen such that truncation doesn't happen - otherwise the model is truncated.
In either case, re-normalization is not needed.

I think it is therefore better to remove re-normalization from all `rd_*` models. 

Are there any other consequences where removing re-normalization could lead to issues?

**Comment by luisfabib** [comment] 2020-03-19 15:56
While I see the issue currently, I see some major problems from the top of my head: 
- All of DeerLab offers the user the fact that they do not need to care about normalization, and in return we can ensure a state of normalization over all DeerLab functions. Removing it specifically from the ``rd_*`` models would be design flaw. 
- We would introduce an important difference in workflow between parametric model fitting and regularization. In the former the distance axis would be computed always automatically, and in the latter the distance axis would always be required to be defined and passed by the user.
- Even if this automation of the distance axis would only be used for fitting, it would be taking away one freedom from users who want to experiment with the distance axis. 
- The same issue is present in model-free fitting and cannot be treated. Treating one method automatically and leaving the other one untreated would lead to confusion. 

Despite this I agree that the problem cannot be left untreated. I might need some more time to think it through.

**Comment by stestoll** [comment] 2020-04-07 16:57
Actually, currently, all parametric models (and the parameter-free ones) are implemented over a fixed user-given `r` range. That means they are all truncated. A two-Gauss model is actually a _truncated_ two-Gauss model.

**Comment by luisfabib** [comment] 2020-04-23 07:21
This issue a duplicate of #62 the discussion will be continued there.

**Closed as completed by luisfabib** 2020-04-23 07:21 UTC
